version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    target-branch: dev/master
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev/master
    open-pull-requests-limit: 5
    labels:
      - ci
    commit-message:
      prefix: "ci"
