//! Go-compatible test vectors for the mieru protocol implementation.
//!
//! All expected values were generated by a Go program using the official
//! mieru v3.29.0 crypto primitives (golang.org/x/crypto). These tests
//! verify that the Rust implementation produces byte-identical output.
//!
//! Run with:  cargo test --test go_compat

use server_mieru_rs::core::crypto::{
    KEY_LEN, KEY_REFRESH_INTERVAL, NONCE_SIZE, TAG_SIZE, decrypt, derive_key, encrypt,
    hashed_password, increment_nonce, time_salt, time_slots_now,
};
use server_mieru_rs::core::metadata::{
    DataMetadata, METADATA_LEN, Metadata, ProtocolType, SessionMetadata,
    current_timestamp_minutes,
};
use server_mieru_rs::core::segment::{
    PACKET_OVERHEAD, STREAM_OVERHEAD, decode_first_stream_segment, decode_packet_segment,
    decode_stream_segment, encode_packet_segment, encode_stream_segment,
};

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}


// =========================================================================
// 1. Key derivation: hashed_password
// =========================================================================

#[test]
fn go_compat_hashed_password_testuser() {
    let hp = hashed_password("testuser", "testpass");
    assert_eq!(
        hex(&hp),
        "623541cef05a0361c2dc377a56f92a2cfb7246a27102c813ccb3c964ed7b26c7"
    );
}

#[test]
fn go_compat_hashed_password_uuid() {
    // mieru business rule: username = password = uuid
    let uuid = "12361d7a-840a-4499-947e-76823e102f00";
    let hp = hashed_password(uuid, uuid);
    assert_eq!(
        hex(&hp),
        "df1111191122953f93ceecf90944196f4eb1280e6826b29c744d22512a2f4ab0"
    );
}

#[test]
fn go_compat_hashed_password_order_matters() {
    // Verify that SHA-256(password || 0x00 || username), not reversed
    let hp_ab = hashed_password("alice", "bob");
    let hp_ba = hashed_password("bob", "alice");
    assert_ne!(hp_ab, hp_ba, "order of username/password must matter");
}

// =========================================================================
// 2. Time salt
// =========================================================================

#[test]
fn go_compat_time_salt_known_values() {
    assert_eq!(
        hex(&time_salt(1714200000)),
        "c041eaa2ad02c4e56724a7e0bd34d788c628be46646901a88ceb032ccd34cdce"
    );
    assert_eq!(
        hex(&time_salt(1714200120)),
        "6a112434ebfad59d930157d51c70881a1db144772b19c07944c549b918f4d5cc"
    );
    assert_eq!(
        hex(&time_salt(0)),
        "af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc"
    );
}

#[test]
fn go_compat_time_salt_uses_seconds_not_minutes() {
    // time_salt(X) = SHA-256(BE64(X)) where X is unix seconds
    // Verify by comparing against manual SHA-256 computation
    use sha2::{Digest, Sha256};
    let ts: u64 = 1714200000;
    let expected = {
        let mut h = Sha256::new();
        h.update(ts.to_be_bytes());
        let d = h.finalize();
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&d);
        arr
    };
    assert_eq!(time_salt(ts), expected);
}

// =========================================================================
// 3. Key derivation: derive_key (PBKDF2)
// =========================================================================

#[test]
fn go_compat_derive_key_testuser() {
    let hp = hashed_password("testuser", "testpass");
    let salt = time_salt(1714200000);
    let key = derive_key(&hp, &salt);
    assert_eq!(
        hex(&key),
        "2a1cd56a1e6f39c81e9468b0e8b1356635bdd771cda54bdc23f82c1a0a6e3824"
    );
}

#[test]
fn go_compat_derive_key_uuid() {
    let uuid = "12361d7a-840a-4499-947e-76823e102f00";
    let hp = hashed_password(uuid, uuid);
    let salt = time_salt(1714200000);
    let key = derive_key(&hp, &salt);
    assert_eq!(
        hex(&key),
        "69057e1d83ebaf91631de07e8c354e69626f9b1ba4370140bc543c53434fd3f4"
    );
}

#[test]
fn go_compat_derive_key_different_salt_different_key() {
    let hp = hashed_password("testuser", "testpass");
    let k1 = derive_key(&hp, &time_salt(1714200000));
    let k2 = derive_key(&hp, &time_salt(1714200120));
    assert_ne!(k1, k2, "different time slots must produce different keys");
}

// =========================================================================
// 4. Nonce increment
// =========================================================================

#[test]
fn go_compat_nonce_increment_sequential() {
    let mut nonce = [0u8; NONCE_SIZE];
    for (i, b) in nonce.iter_mut().enumerate() {
        *b = i as u8;
    }
    assert_eq!(
        hex(&nonce),
        "000102030405060708090a0b0c0d0e0f1011121314151617"
    );

    increment_nonce(&mut nonce);
    assert_eq!(
        hex(&nonce),
        "000102030405060708090a0b0c0d0e0f1011121314151618"
    );

    increment_nonce(&mut nonce);
    assert_eq!(
        hex(&nonce),
        "000102030405060708090a0b0c0d0e0f1011121314151619"
    );
}

#[test]
fn go_compat_nonce_increment_carry() {
    let mut nonce = [0u8; NONCE_SIZE];
    nonce[NONCE_SIZE - 1] = 0xff;
    nonce[NONCE_SIZE - 2] = 0xff;
    assert_eq!(
        hex(&nonce),
        "00000000000000000000000000000000000000000000ffff"
    );

    increment_nonce(&mut nonce);
    assert_eq!(
        hex(&nonce),
        "000000000000000000000000000000000000000000010000"
    );
}

#[test]
fn go_compat_nonce_increment_full_wrap() {
    let mut nonce = [0xffu8; NONCE_SIZE];
    increment_nonce(&mut nonce);
    assert_eq!(nonce, [0u8; NONCE_SIZE]);
}

// =========================================================================
// 5. XChaCha20-Poly1305 encrypt
// =========================================================================

fn test_key() -> [u8; KEY_LEN] {
    let hp = hashed_password("testuser", "testpass");
    let salt = time_salt(1714200000);
    derive_key(&hp, &salt)
}

fn sequential_nonce() -> [u8; NONCE_SIZE] {
    let mut n = [0u8; NONCE_SIZE];
    for (i, b) in n.iter_mut().enumerate() {
        *b = i as u8;
    }
    n
}

#[test]
fn go_compat_encrypt_known_value() {
    let key = test_key();
    let nonce = sequential_nonce();
    let ct = encrypt(&key, &nonce, b"hello, mieru!");
    assert_eq!(
        hex(&ct),
        "65f0b08a5d499bb8ac3180c76848dc4c4f368e6f1ff0f638fecff3b694"
    );
    assert_eq!(ct.len(), 13 + TAG_SIZE);
}

#[test]
fn go_compat_encrypt_decrypt_roundtrip() {
    let key = test_key();
    let nonce = sequential_nonce();
    let ct = encrypt(&key, &nonce, b"hello, mieru!");
    let pt = decrypt(&key, &nonce, &ct).expect("decrypt must succeed");
    assert_eq!(pt, b"hello, mieru!");
}

#[test]
fn go_compat_encrypt_empty_produces_tag_only() {
    let key = test_key();
    let nonce = sequential_nonce();
    let ct = encrypt(&key, &nonce, b"");
    assert_eq!(ct.len(), TAG_SIZE);
    let pt = decrypt(&key, &nonce, &ct).unwrap();
    assert!(pt.is_empty());
}

// =========================================================================
// 6. Metadata encode (exact byte layout)
// =========================================================================

#[test]
fn go_compat_session_metadata_encode() {
    let meta = SessionMetadata {
        protocol_type: ProtocolType::OpenSessionRequest,
        timestamp: 29614080,
        session_id: 0xDEADBEEF,
        sequence: 42,
        status_code: 0,
        payload_length: 128,
        suffix_padding_length: 16,
    };
    let buf = meta.encode();
    assert_eq!(
        hex(&buf),
        "020001c3e000deadbeef0000002a000080100000000000000000000000000000"
    );
}

#[test]
fn go_compat_data_metadata_encode() {
    let meta = DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: 29614080,
        session_id: 0xDEADBEEF,
        sequence: 100,
        unack_seq: 99,
        window_size: 256,
        fragment_number: 3,
        prefix_padding_length: 16,
        payload_length: 1400,
        suffix_padding_length: 8,
    };
    let buf = meta.encode();
    assert_eq!(
        hex(&buf),
        "060001c3e000deadbeef00000064000000630100031005780800000000000000"
    );
}

#[test]
fn go_compat_metadata_decode_roundtrip_all_types() {
    for pt_val in 0u8..=9 {
        let pt = ProtocolType::from_u8(pt_val).unwrap();
        if pt.is_session_type() {
            let meta = SessionMetadata {
                protocol_type: pt,
                timestamp: current_timestamp_minutes(),
                session_id: 0x12345678,
                sequence: 99,
                status_code: 0,
                payload_length: 512,
                suffix_padding_length: 8,
            };
            let buf = meta.encode();
            let decoded = Metadata::decode(&buf).expect("decode session");
            match decoded {
                Metadata::Session(s) => {
                    assert_eq!(s.protocol_type, pt);
                    assert_eq!(s.session_id, 0x12345678);
                    assert_eq!(s.sequence, 99);
                    assert_eq!(s.payload_length, 512);
                }
                _ => panic!("expected Session variant for type {pt_val}"),
            }
        } else {
            let meta = DataMetadata {
                protocol_type: pt,
                timestamp: current_timestamp_minutes(),
                session_id: 0x87654321,
                sequence: 200,
                unack_seq: 150,
                window_size: 1024,
                fragment_number: 2,
                prefix_padding_length: 4,
                payload_length: 2000,
                suffix_padding_length: 12,
            };
            let buf = meta.encode();
            let decoded = Metadata::decode(&buf).expect("decode data");
            match decoded {
                Metadata::Data(d) => {
                    assert_eq!(d.protocol_type, pt);
                    assert_eq!(d.session_id, 0x87654321);
                    assert_eq!(d.sequence, 200);
                    assert_eq!(d.unack_seq, 150);
                    assert_eq!(d.window_size, 1024);
                    assert_eq!(d.fragment_number, 2);
                    assert_eq!(d.prefix_padding_length, 4);
                    assert_eq!(d.payload_length, 2000);
                    assert_eq!(d.suffix_padding_length, 12);
                }
                _ => panic!("expected Data variant for type {pt_val}"),
            }
        }
    }
}

// =========================================================================
// 7. TCP segment: full wire format verification against Go output
// =========================================================================

#[test]
fn go_compat_tcp_first_segment_wire_format() {
    let key = test_key();
    let mut nonce = [0u8; NONCE_SIZE];
    for (i, b) in nonce.iter_mut().enumerate() {
        *b = (i as u8) * 3;
    }

    let meta = Metadata::Session(SessionMetadata {
        protocol_type: ProtocolType::OpenSessionRequest,
        timestamp: 29614080,
        session_id: 0x00000001,
        sequence: 0,
        status_code: 0,
        payload_length: 5,
        suffix_padding_length: 0,
    });
    let payload = b"hello";

    let wire = encode_stream_segment(&key, &mut nonce, &meta, payload, &[], &[], true);

    assert_eq!(
        hex(&wire),
        "000306090c0f1215181b1e2124272a2d303336393c3f4245\
77cdc76bfbc864649c2b46ec1b9146c15f919f954e26d2fae08f5639f2b0b01a4af4d424cfdadd27e7e0cc619eea70cb\
462474411787bbdedd3b8073d184f667c57b3e3119"
    );
    assert_eq!(wire.len(), 93); // 24 nonce + 48 enc_meta + 21 enc_payload

    // Verify nonce advanced by 2
    assert_eq!(
        hex(&nonce),
        "000306090c0f1215181b1e2124272a2d303336393c3f4247"
    );
}

#[test]
fn go_compat_tcp_first_segment_encode_decode_roundtrip() {
    // The Go wire vector uses a fixed timestamp that fails is_timestamp_valid(),
    // so we verify roundtrip with a current timestamp instead.
    // Byte-exact Go compatibility is proven by go_compat_tcp_first_segment_wire_format.
    let key = test_key();
    let mut nonce = [0u8; NONCE_SIZE];
    for (i, b) in nonce.iter_mut().enumerate() {
        *b = (i as u8) * 3;
    }

    let meta = Metadata::Session(SessionMetadata {
        protocol_type: ProtocolType::OpenSessionRequest,
        timestamp: current_timestamp_minutes(), // use current time
        session_id: 0x00000001,
        sequence: 0,
        status_code: 0,
        payload_length: 5,
        suffix_padding_length: 0,
    });
    let payload = b"hello";

    let mut enc_nonce = nonce;
    let wire = encode_stream_segment(&key, &mut enc_nonce, &meta, payload, &[], &[], true);

    let (nonce_after, dec_meta, dec_payload) =
        decode_first_stream_segment(&key, &wire).expect("decode segment");

    assert_eq!(dec_payload, b"hello");
    assert_eq!(nonce_after, enc_nonce, "nonce must be in sync after roundtrip");
    match dec_meta {
        Metadata::Session(s) => {
            assert_eq!(s.protocol_type, ProtocolType::OpenSessionRequest);
            assert_eq!(s.session_id, 1);
            assert_eq!(s.payload_length, 5);
        }
        _ => panic!("expected Session metadata"),
    }
}

// =========================================================================
// 8. UDP packet: full wire format verification against Go output
// =========================================================================

#[test]
fn go_compat_udp_packet_wire_format() {
    let key = test_key();
    let mut nonce = [0u8; NONCE_SIZE];
    for (i, b) in nonce.iter_mut().enumerate() {
        *b = (i as u8) * 7 + 1;
    }

    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: 29614080,
        session_id: 0x00000010,
        sequence: 1,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 0,
        payload_length: 8, // "udp data".len()
        suffix_padding_length: 0,
    });
    let payload = b"udp data";

    let wire = encode_packet_segment(&key, &nonce, &meta, payload, &[], &[]);

    assert_eq!(
        hex(&wire),
        "01080f161d242b323940474e555c636a71787f868d949ba2\
794f61c6fa0a91563404bc1f352ec5780d90561a92f5f839326f1fcbe505fdc3d8c8956a782b0e05aa041aedfac3e220\
0a2b10257e6be5370080086624757115da01d57081d33723"
    );
    assert_eq!(wire.len(), 96); // 24 nonce + 48 enc_meta + 24 enc_payload
}

#[test]
fn go_compat_udp_packet_encode_decode_roundtrip() {
    // The Go wire vector uses a fixed timestamp that fails is_timestamp_valid(),
    // so we verify roundtrip with a current timestamp instead.
    // Byte-exact Go compatibility is proven by go_compat_udp_packet_wire_format.
    let key = test_key();
    let mut nonce = [0u8; NONCE_SIZE];
    for (i, b) in nonce.iter_mut().enumerate() {
        *b = (i as u8) * 7 + 1;
    }

    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(), // use current time
        session_id: 0x00000010,
        sequence: 1,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 0,
        payload_length: 8,
        suffix_padding_length: 0,
    });
    let payload = b"udp data";

    let wire = encode_packet_segment(&key, &nonce, &meta, payload, &[], &[]);
    let (dec_nonce, dec_meta, dec_payload) =
        decode_packet_segment(&key, &wire).expect("decode UDP packet");

    assert_eq!(dec_payload, b"udp data");
    assert_eq!(dec_nonce, nonce, "UDP nonce must match original");
    match dec_meta {
        Metadata::Data(d) => {
            assert_eq!(d.protocol_type, ProtocolType::DataClientToServer);
            assert_eq!(d.session_id, 0x10);
            assert_eq!(d.sequence, 1);
            assert_eq!(d.payload_length, 8);
        }
        _ => panic!("expected Data metadata"),
    }
}

#[test]
fn go_compat_udp_same_nonce_for_meta_and_payload() {
    // Core protocol invariant: UDP uses the SAME nonce for both metadata and
    // payload encryption. Verify this by manually encrypting with the same
    // nonce and comparing to encode_packet_segment output.
    let key = test_key();
    let nonce = sequential_nonce();
    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 0,
        payload_length: 4,
        suffix_padding_length: 0,
    });
    let payload = b"test";

    let wire = encode_packet_segment(&key, &nonce, &meta, payload, &[], &[]);

    // Manually extract and verify
    let wire_nonce = &wire[..NONCE_SIZE];
    assert_eq!(wire_nonce, &nonce[..]);

    let enc_meta = &wire[NONCE_SIZE..NONCE_SIZE + METADATA_LEN + TAG_SIZE];
    let enc_payload = &wire[NONCE_SIZE + METADATA_LEN + TAG_SIZE..];

    // Both must decrypt with the SAME nonce
    let dec_meta = decrypt(&key, &nonce, enc_meta).expect("meta decrypt");
    let dec_payload = decrypt(&key, &nonce, enc_payload).expect("payload decrypt with SAME nonce");
    assert_eq!(dec_meta, meta.encode());
    assert_eq!(dec_payload, b"test");
}

// =========================================================================
// 9. TCP nonce synchronization: multi-segment stress
// =========================================================================

#[test]
fn go_compat_tcp_nonce_sync_10_segments() {
    let key = test_key();
    let mut enc_nonce = sequential_nonce();

    let mut segments = Vec::new();
    for i in 0u32..10 {
        let payload = format!("segment {i} with some data padding xxxxxx");
        let meta = Metadata::Data(DataMetadata {
            protocol_type: ProtocolType::DataClientToServer,
            timestamp: current_timestamp_minutes(),
            session_id: 0xAABBCCDD,
            sequence: i,
            unack_seq: 0,
            window_size: 256,
            fragment_number: 0,
            prefix_padding_length: 0,
            payload_length: payload.len() as u16,
            suffix_padding_length: 0,
        });
        let include_nonce = i == 0;
        let seg = encode_stream_segment(
            &key,
            &mut enc_nonce,
            &meta,
            payload.as_bytes(),
            &[],
            &[],
            include_nonce,
        );
        segments.push((seg, payload));
    }

    // Decode all segments, verify nonce stays in sync
    let (mut dec_nonce, _, dec_payload) =
        decode_first_stream_segment(&key, &segments[0].0).expect("decode seg 0");
    assert_eq!(dec_payload, segments[0].1.as_bytes());

    for i in 1..10 {
        let (_, dec_payload) =
            decode_stream_segment(&key, &mut dec_nonce, &segments[i].0).expect(&format!("seg {i}"));
        assert_eq!(dec_payload, segments[i].1.as_bytes(), "payload mismatch seg {i}");
    }

    assert_eq!(enc_nonce, dec_nonce, "nonce desync after 10 segments");
}

#[test]
fn go_compat_tcp_nonce_sync_with_empty_payloads() {
    // Mix of segments with and without payload.
    // Empty payload: nonce advances by 1 (metadata only).
    // Non-empty payload: nonce advances by 2 (metadata + payload).
    let key = test_key();
    let mut enc_nonce = sequential_nonce();
    let original_nonce = sequential_nonce();

    let payloads: [&[u8]; 5] = [b"data", b"", b"more", b"", b"end"];
    let mut segments = Vec::new();

    for (i, &p) in payloads.iter().enumerate() {
        let meta = if p.is_empty() {
            // Session control (no payload)
            Metadata::Session(SessionMetadata {
                protocol_type: ProtocolType::CloseSessionRequest,
                timestamp: current_timestamp_minutes(),
                session_id: 0x11,
                sequence: i as u32,
                status_code: 0,
                payload_length: 0,
                suffix_padding_length: 0,
            })
        } else {
            Metadata::Data(DataMetadata {
                protocol_type: ProtocolType::DataClientToServer,
                timestamp: current_timestamp_minutes(),
                session_id: 0x11,
                sequence: i as u32,
                unack_seq: 0,
                window_size: 256,
                fragment_number: 0,
                prefix_padding_length: 0,
                payload_length: p.len() as u16,
                suffix_padding_length: 0,
            })
        };
        let include_nonce = i == 0;
        let seg =
            encode_stream_segment(&key, &mut enc_nonce, &meta, p, &[], &[], include_nonce);
        segments.push(seg);
    }

    // Expected nonce advancement: +2, +1, +2, +1, +2 = +8 total
    let mut expected_nonce = original_nonce;
    for _ in 0..8 {
        increment_nonce(&mut expected_nonce);
    }
    assert_eq!(
        enc_nonce, expected_nonce,
        "encoder nonce should advance by 8 (2+1+2+1+2)"
    );

    // Decode and verify sync
    let (mut dec_nonce, _, p) =
        decode_first_stream_segment(&key, &segments[0]).expect("decode seg 0");
    assert_eq!(p, payloads[0]);

    for i in 1..5 {
        let (_, p) =
            decode_stream_segment(&key, &mut dec_nonce, &segments[i]).expect(&format!("seg {i}"));
        assert_eq!(p, payloads[i], "payload mismatch seg {i}");
    }

    assert_eq!(enc_nonce, dec_nonce, "nonce desync with empty payloads");
}

// =========================================================================
// 10. Time slot computation
// =========================================================================

#[test]
fn go_compat_time_slots_properties() {
    let slots = time_slots_now();

    // All slots are multiples of KEY_REFRESH_INTERVAL (120s)
    for &slot in &slots {
        assert_eq!(
            slot % KEY_REFRESH_INTERVAL,
            0,
            "slot {slot} not a multiple of {KEY_REFRESH_INTERVAL}"
        );
    }

    // Spacing is exactly KEY_REFRESH_INTERVAL
    assert_eq!(slots[1] - slots[0], KEY_REFRESH_INTERVAL);
    assert_eq!(slots[2] - slots[1], KEY_REFRESH_INTERVAL);

    // Current time should be within [-half, +half) of the middle slot
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    let half = KEY_REFRESH_INTERVAL / 2;
    assert!(
        now.abs_diff(slots[1]) <= half,
        "middle slot {s} too far from now {now}",
        s = slots[1]
    );
}

#[test]
fn go_compat_time_slots_rounding_matches_go() {
    // Go's time.Round(2*time.Minute) rounds to nearest, ties go away from zero.
    // Rust: ((now + 60) / 120) * 120
    // Test boundary cases manually.

    // Exactly at a boundary: now=240 → round to 240
    let round = |now: u64| ((now + 60) / 120) * 120;
    assert_eq!(round(240), 240);

    // Just before boundary: now=239 → round to 240
    assert_eq!(round(239), 240);

    // Just after boundary: now=241 → round to 240
    assert_eq!(round(241), 240);

    // Midpoint (tie): now=300 → 300+60=360 → 360/120=3 → 3*120=360
    // This matches Go's "tie goes up" since Round in Go rounds to nearest
    assert_eq!(round(300), 360);

    // Just before midpoint: now=299 → 299+60=359 → 359/120=2 → 240
    assert_eq!(round(299), 240);

    // Edge: now=0 → round to 0
    assert_eq!(round(0), 0);
    assert_eq!(round(59), 0);
    assert_eq!(round(60), 120);
}

// =========================================================================
// 11. Overhead constants
// =========================================================================

#[test]
fn go_compat_overhead_constants() {
    // Go: streamOverhead = MetadataLength + DefaultOverhead*2 = 32 + 32 = 64
    assert_eq!(STREAM_OVERHEAD, 64);
    assert_eq!(STREAM_OVERHEAD, METADATA_LEN + TAG_SIZE * 2);

    // Go: packetOverhead = NonceSize + MetadataLength + DefaultOverhead*2 = 24+32+32 = 88
    assert_eq!(PACKET_OVERHEAD, 88);
    assert_eq!(PACKET_OVERHEAD, NONCE_SIZE + METADATA_LEN + TAG_SIZE * 2);
}

// =========================================================================
// 12. Segment with padding
// =========================================================================

#[test]
fn go_compat_tcp_segment_with_padding() {
    let key = test_key();
    let mut enc_nonce = sequential_nonce();
    let mut dec_nonce = sequential_nonce();

    let prefix_pad = vec![0xAAu8; 16];
    let suffix_pad = vec![0xBBu8; 8];
    let payload = b"padded payload";

    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 16,
        payload_length: payload.len() as u16,
        suffix_padding_length: 8,
    });

    let wire = encode_stream_segment(
        &key,
        &mut enc_nonce,
        &meta,
        payload,
        &prefix_pad,
        &suffix_pad,
        false,
    );

    // Wire: [enc_meta(48)] [prefix(16)] [enc_payload(14+16=30)] [suffix(8)]
    let expected_len = METADATA_LEN + TAG_SIZE + 16 + payload.len() + TAG_SIZE + 8;
    assert_eq!(wire.len(), expected_len);

    let (dec_meta, dec_payload) =
        decode_stream_segment(&key, &mut dec_nonce, &wire).expect("decode padded");
    assert_eq!(dec_payload, payload);
    match dec_meta {
        Metadata::Data(d) => {
            assert_eq!(d.prefix_padding_length, 16);
            assert_eq!(d.suffix_padding_length, 8);
        }
        _ => panic!("expected Data"),
    }
    assert_eq!(enc_nonce, dec_nonce);
}

#[test]
fn go_compat_udp_packet_with_padding() {
    let key = test_key();
    let nonce = sequential_nonce();
    let prefix_pad = vec![0xCCu8; 12];
    let suffix_pad = vec![0xDDu8; 4];
    let payload = b"udp padded";

    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(),
        session_id: 2,
        sequence: 0,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 12,
        payload_length: payload.len() as u16,
        suffix_padding_length: 4,
    });

    let wire = encode_packet_segment(&key, &nonce, &meta, payload, &prefix_pad, &suffix_pad);

    // Wire: [nonce(24)] [enc_meta(48)] [prefix(12)] [enc_payload(10+16=26)] [suffix(4)]
    let expected_len = NONCE_SIZE + METADATA_LEN + TAG_SIZE + 12 + payload.len() + TAG_SIZE + 4;
    assert_eq!(wire.len(), expected_len);

    let (_, dec_meta, dec_payload) =
        decode_packet_segment(&key, &wire).expect("decode padded UDP");
    assert_eq!(dec_payload, payload);
    match dec_meta {
        Metadata::Data(d) => {
            assert_eq!(d.prefix_padding_length, 12);
            assert_eq!(d.suffix_padding_length, 4);
        }
        _ => panic!("expected Data"),
    }
}

// =========================================================================
// 13. Error cases
// =========================================================================

#[test]
fn go_compat_wrong_key_rejects() {
    let key = test_key();
    let nonce = sequential_nonce();
    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 0,
        payload_length: 5,
        suffix_padding_length: 0,
    });

    // TCP
    let mut enc_nonce = nonce;
    let wire = encode_stream_segment(&key, &mut enc_nonce, &meta, b"hello", &[], &[], true);
    let mut wrong_key = key;
    wrong_key[0] ^= 0xFF;
    assert!(decode_first_stream_segment(&wrong_key, &wire).is_none());

    // UDP
    let udp_wire = encode_packet_segment(&key, &nonce, &meta, b"hello", &[], &[]);
    assert!(decode_packet_segment(&wrong_key, &udp_wire).is_none());
}

#[test]
fn go_compat_truncated_data_rejects() {
    let key = test_key();
    let mut nonce = sequential_nonce();
    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 0,
        payload_length: 5,
        suffix_padding_length: 0,
    });

    // TCP: truncate the wire data
    let wire = encode_stream_segment(&key, &mut nonce, &meta, b"hello", &[], &[], true);
    for truncate_at in [0, 1, NONCE_SIZE, NONCE_SIZE + METADATA_LEN, wire.len() - 1] {
        assert!(
            decode_first_stream_segment(&key, &wire[..truncate_at]).is_none(),
            "should reject truncation at {truncate_at}"
        );
    }

    // UDP: truncate
    let udp_wire = encode_packet_segment(&key, &sequential_nonce(), &meta, b"hello", &[], &[]);
    for truncate_at in [0, 1, NONCE_SIZE, NONCE_SIZE + METADATA_LEN, udp_wire.len() - 1] {
        assert!(
            decode_packet_segment(&key, &udp_wire[..truncate_at]).is_none(),
            "UDP should reject truncation at {truncate_at}"
        );
    }
}

#[test]
fn go_compat_corrupted_ciphertext_rejects() {
    let key = test_key();
    let nonce = sequential_nonce();
    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 0,
        payload_length: 5,
        suffix_padding_length: 0,
    });

    // TCP
    let mut enc_nonce = nonce;
    let mut wire = encode_stream_segment(&key, &mut enc_nonce, &meta, b"hello", &[], &[], true);
    // Flip bit in encrypted metadata region
    wire[NONCE_SIZE] ^= 0x01;
    assert!(decode_first_stream_segment(&key, &wire).is_none());

    // UDP
    let mut udp_wire = encode_packet_segment(&key, &nonce, &meta, b"hello", &[], &[]);
    udp_wire[NONCE_SIZE + 1] ^= 0x01;
    assert!(decode_packet_segment(&key, &udp_wire).is_none());
}

// =========================================================================
// 14. TCP vs UDP nonce behavior difference
// =========================================================================

#[test]
fn go_compat_tcp_nonce_mutates_udp_nonce_does_not() {
    let key = test_key();
    let meta = Metadata::Data(DataMetadata {
        protocol_type: ProtocolType::DataClientToServer,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        unack_seq: 0,
        window_size: 256,
        fragment_number: 0,
        prefix_padding_length: 0,
        payload_length: 4,
        suffix_padding_length: 0,
    });

    // TCP: nonce is mutable and advances
    let original = sequential_nonce();
    let mut tcp_nonce = original;
    encode_stream_segment(&key, &mut tcp_nonce, &meta, b"test", &[], &[], false);
    assert_ne!(tcp_nonce, original, "TCP nonce must advance");

    // UDP: nonce is immutable (taken by reference)
    let udp_nonce = sequential_nonce();
    encode_packet_segment(&key, &udp_nonce, &meta, b"test", &[], &[]);
    assert_eq!(udp_nonce, original, "UDP nonce must NOT be modified");
}

// =========================================================================
// 15. Full client-server simulation (loopback)
// =========================================================================

#[test]
fn go_compat_full_tcp_loopback_simulation() {
    // Simulate a client sending 3 segments, server receiving and responding.
    // Verifies that independent send/recv nonces work correctly.
    let key = test_key();

    // Client side
    let mut client_send_nonce = sequential_nonce();

    // Server side (will be initialized after reading first segment)
    let mut server_recv_nonce: [u8; NONCE_SIZE];
    let mut server_send_nonce = {
        let mut n = [0u8; NONCE_SIZE];
        n[0] = 0xAA; // Different from client
        n
    };

    // -- Client sends OpenSessionRequest --
    let open_meta = Metadata::Session(SessionMetadata {
        protocol_type: ProtocolType::OpenSessionRequest,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        status_code: 0,
        payload_length: 6,
        suffix_padding_length: 0,
    });
    let seg1 = encode_stream_segment(
        &key,
        &mut client_send_nonce,
        &open_meta,
        b"addr01",
        &[],
        &[],
        true, // first segment
    );

    // -- Server decodes first segment --
    let (nonce_after, meta, payload) =
        decode_first_stream_segment(&key, &seg1).expect("server decode first");
    server_recv_nonce = nonce_after;
    assert_eq!(payload, b"addr01");
    assert_eq!(meta.protocol_type(), ProtocolType::OpenSessionRequest);

    // -- Server sends OpenSessionResponse (first response, includes nonce) --
    let resp_meta = Metadata::Session(SessionMetadata {
        protocol_type: ProtocolType::OpenSessionResponse,
        timestamp: current_timestamp_minutes(),
        session_id: 1,
        sequence: 0,
        status_code: 0,
        payload_length: 0,
        suffix_padding_length: 0,
    });
    let resp1 = encode_stream_segment(
        &key,
        &mut server_send_nonce,
        &resp_meta,
        &[],
        &[],
        &[],
        true, // server's first send
    );

    // -- Client decodes server's first response --
    let (mut client_recv_nonce, meta, payload) =
        decode_first_stream_segment(&key, &resp1).expect("client decode first response");
    assert_eq!(meta.protocol_type(), ProtocolType::OpenSessionResponse);
    assert!(payload.is_empty());

    // -- Client sends 2 data segments --
    for seq in 1..=2u32 {
        let data = format!("data #{seq}");
        let data_meta = Metadata::Data(DataMetadata {
            protocol_type: ProtocolType::DataClientToServer,
            timestamp: current_timestamp_minutes(),
            session_id: 1,
            sequence: seq,
            unack_seq: 0,
            window_size: 256,
            fragment_number: 0,
            prefix_padding_length: 0,
            payload_length: data.len() as u16,
            suffix_padding_length: 0,
        });
        let seg = encode_stream_segment(
            &key,
            &mut client_send_nonce,
            &data_meta,
            data.as_bytes(),
            &[],
            &[],
            false,
        );

        // Server decodes
        let (_, payload) =
            decode_stream_segment(&key, &mut server_recv_nonce, &seg).expect("server decode data");
        assert_eq!(payload, data.as_bytes());

        // Server echoes back
        let echo_meta = Metadata::Data(DataMetadata {
            protocol_type: ProtocolType::DataServerToClient,
            timestamp: current_timestamp_minutes(),
            session_id: 1,
            sequence: seq,
            unack_seq: seq,
            window_size: 256,
            fragment_number: 0,
            prefix_padding_length: 0,
            payload_length: payload.len() as u16,
            suffix_padding_length: 0,
        });
        let echo_seg = encode_stream_segment(
            &key,
            &mut server_send_nonce,
            &echo_meta,
            &payload,
            &[],
            &[],
            false,
        );

        // Client decodes echo
        let (_, echoed) = decode_stream_segment(&key, &mut client_recv_nonce, &echo_seg)
            .expect("client decode echo");
        assert_eq!(echoed, data.as_bytes(), "echo mismatch for seq {seq}");
    }

    // Verify both nonce pairs are in sync
    assert_eq!(client_send_nonce, server_recv_nonce, "send/recv nonce desync");
    assert_eq!(
        server_send_nonce, client_recv_nonce,
        "server send / client recv nonce desync"
    );
}
